# Generated by Django 4.1.7 on 2023-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='image_in',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
