# Generated by Django 4.1.7 on 2023-04-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="log",
            old_name="vehicle_id",
            new_name="vehicle",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="user_id",
            new_name="user",
        ),
    ]
