# Generated by Django 4.1.7 on 2023-05-04 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_log_image_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
