# Generated by Django 4.1.7 on 2023-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_delete_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='vehicle',
            field=models.CharField(max_length=255),
        ),
    ]
