# Generated by Django 4.1.7 on 2023-04-07 08:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_type_alter_account_address_alter_account_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_pic",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
