# Generated by Django 4.1.7 on 2023-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_log_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='Member'),
        ),
    ]
