# Generated by Django 4.1.7 on 2023-06-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_log_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='parking_fee',
            field=models.CharField(db_column='balance', max_length=100),
        ),
    ]
