# Generated by Django 4.1.7 on 2023-04-11 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_vehicle_vehicle_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
