# Generated by Django 4.1.7 on 2023-04-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_image_type_delete_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
