# Generated by Django 4.1.7 on 2023-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_alter_account_parking_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='parking_fee',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
