# Generated by Django 4.1.7 on 2023-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_remove_account_parking_fee_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='parking_fee',
            field=models.FloatField(default=0),
        ),
    ]
